version: '3'

services:
  localstack:
    image: localstack/localstack:0.10.1.2
    ports:
      - "4567-4593:4567-4593"
    environment:
      - SERVICES=serverless
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
    volumes:
      - "${TMPDIR}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"